
["Server Configs"]
	#Canister Capacity in mB
	"Capacity of Canisters" = 4000
	#Canister can be filled by spouts
	"Canister can be filled by spouts" = true
	#Combustibles do boom boom when on fire
	"Combustibles blow up" = true

	["Server Configs"."Diesel Engines"]
		#Turbocharged Diesel Engine Speed Multiplier
		"Turbocharged Diesel Engine Speed Multiplier" = 2.0
		#Turbocharged Diesel Engine Burn Rate Multiplier
		"Turbocharged Diesel Engine Burn Rate Multiplier" = 1.0

	["Server Configs"."Oil Config"]
		#Normal oil chunks oil amount multiplier
		"Normal oil chunks oil amount multiplier" = 1.0
		#High oil chunks oil amount multiplier
		"High oil chunks oil amount multiplier" = 1.0
		#Max Oil Scanner Level
		"Max Oil Scanner Level" = 10000
		#Normal oil chunks percentage
		#Range: 0.0 ~ 100.0
		"Normal oil chunks percentage" = 10.0
		#High oil chunks percentage
		#Range: 0.0 ~ 100.0
		"High oil chunks percentage" = 10.0

		["Server Configs"."Oil Config".Distillation]
			#Whenever wide Distillation Towers go faster than the thin ones
			"Wide Distillation Tower Distill Faster" = true
			#Height of Distillation Tower level
			#Range: 1 ~ 3
			"Height of Distillation Tower level" = 1

